### ISSUE TITLE
Create Tweet when replying to a tweet expects string, gets integer

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10147]
### App
Create Tweet when replying to a tweet expects string, gets integer

### Summary:
Create Tweet when replying to a tweet expects string, gets integer

### Details:
Using the create tweet trigger, I am sending in some text to Pipedream, I am retrieving the tweet Id to reply to from a data store using this "{{steps.get_record_or_create.$return_value}}" as the "In Reply To Tweet (ID)" parameter.

I get this:
message":"$.reply.in_reply_to_tweet_id: integer found, string expected"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"

Details:

Input:
{"debug":true,"baseURL":"https://api.twitter.com/2","method":"POST","url":"/tweets","data":{"text":"This is my response to you","reply":{"in_reply_to_tweet_id":1752709105280598000}},"headers":{<REDACTED>}}

That results in an error:

 at null.settle
(/tmp/__pdg__/dist/code/768be63505a8312c35b084103267dcae6e2d67f03eb5bdd41df475cad95e860c/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:1967:12)
    at Unzip.handleStreamEnd (/tmp/__pdg__/dist/code/768be63505a8312c35b084103267dcae6e2d67f03eb5bdd41df475cad95e860c/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:3066:11)
    at Unzip.emit (node:events:529:35)
    at null.endReadableNT (node:internal/streams/readable:1368:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.callAxios (/tmp/__pdg__/dist/code/768be63505a8312c35b084103267dcae6e2d67f03eb5bdd41df475cad95e860c/node_modules/.pnpm/@pipedream+platform@1.6.0/node_modules/@pipedream/platform/dist/axios.js:110:26)
    at Object._httpRequest (file:///tmp/__pdg__/dist/code/768be63505a8312c35b084103267dcae6e2d67f03eb5bdd41df475cad95e860c/code/app/twitter.app.mjs:119:32)
    at Object.run (file:///tmp/__pdg__/dist/code/768be63505a8312c35b084103267dcae6e2d67f03eb5bdd41df475cad95e860c/code/actions/create-tweet/create-tweet.mjs:76:26)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:783:28)
 {
 message: '{"errors":[{"parameters":{"$.reply.in_reply_to_tweet_id":["1752709105280598000"]},"message":"$.reply.in_reply_to_tweet_id: integer found, string expected"}],"title":"Invalid Request","detail":"One or more parameters to your request was invalid.","type":"https://api.twitter.com/2/problems/invalid-request"}',
  name: 'AxiosError - Request failed with status code 400',
  code: 'ERR_BAD_REQUEST',

### Screenshots:

![Screenshot](https://storage.tally.so/private/twitterid.png?id=OaKEga&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ik9hS0VnYSIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwNjcxNDYzNH0.NlkCtVLQU5M3P3kTn4OZtblX-5UHw38zNavlXXWD1ys&signature=9ac44490a1cbda39628478822a73b33677dd979b2f867754b8ec5db01ad51050)

**Comment by malexanderlim** [comment]
Closing the issue as this was reported as user error.
