### ISSUE TITLE
[BUG] OneDrive - New File in Folder trigger does not emit event

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#10225]
**Describe the bug**
A user create the New File in Folder trigger
![image](https://github.com/PipedreamHQ/pipedream/assets/18277920/0298721d-496f-4d6d-b70b-994f75f8a6d4)

But there's no event emitted due to an error
```
2024-02-05T19:26:34
error
TypeError: Cannot read properties of undefined (reading 'file')
at Object.isItemRelevant (file:///var/task/user/sources/new-file-in-folder/new-file-in-folder.mjs:30:27)
at Object._processEventsFromDeltaLink (file:///var/task/user/sources/common/base.mjs:165:15)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async Object.run (file:///var/task/user/sources/common/base.mjs:294:3)
at async /var/task/index.js:122:11
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async exports.main [as handler] (/var/task/index.js:60:20)
```

**To Reproduce**
If the file gets created on PC and synced to the cloud, I don't get anything triggered. Once I get that error it seems the workflow is stuck in that state an nothing is triggered

**Comment by philcart** [comment]
So I am the user mentioned above.
Just to add to this, the same error occurs if I create the file on my mobile and sync to cloud.
Cheers

**Comment by datamyers** [comment]
I have this issue currently.  Seems to be the same, at least.  I continue to get this error
![image](https://github.com/PipedreamHQ/pipedream/assets/4441370/392b5a76-4ff1-490f-a74a-7a72dcc394d3)

Am I doing something wrong?

**Comment by michelle0927** [comment]
Hi, @datamyers Have you tried recreating the source to make sure you're using the most recent version?

**Comment by datamyers** [comment]
Thank you!  That worked.

Figured I missed something.

*~CJ Myers*
