### ISSUE TITLE
[BUG] mySQL app - executing SP

### ISSUE THREAD

**Issue by sharafi1981** [PipedreamHQ/pipedream#10480]
When executing a stored procedure that doesn't yield any output, the following error is generated:

TypeError
(intermediate value) is not iterable

DETAILS
    at Object.executeStoredProcedure (file:///tmp/__pdg__/dist/code/abb72a0437486810d1e2551fea245f959fd0a10320d8233e0c4107e2a50ac0cb/code/mysql.app.mjs:337:11)
    at Object.run (file:///tmp/__pdg__/dist/code/abb72a0437486810d1e2551fea245f959fd0a10320d8233e0c4107e2a50ac0cb/code/actions/execute-stored-procedure/execute-stored-procedure.mjs:30:20)
    at null.executeComponent (/var/task/launch_worker.js:294:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:791:28)

**Comment by andrewjschuang** [comment]
Current suspicion is the error is located in [this destructuring statement](https://github.com/PipedreamHQ/pipedream/blob/master/components/mysql/mysql.app.mjs#L336). 
@sharafi1981 reported that the error happens if the stored procedure does not return any output
