### ISSUE TITLE
ByBit Generic API Call with ByBit API on New Worksheet (Instant) from Google Sheets API

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#10799]
### App
ByBit Generic API Call with ByBit API on New Worksheet (Instant) from Google Sheets API

### Summary:
Getting error: Cannot convert undefined or null to object

### Details:
Testing the WF I am getting following error

Cannot convert undefined or null to object
  at Function.entries (null:null:null)
    at Object.getAllValidParameters (file:///tmp/__pdg__/dist/code/37eeba0c55c171ce405fd46f7606f6f15454920f510a10ca38c8601925195b50/code/bybit.app.mjs:391:14)
    at Object.makeRequest (file:///tmp/__pdg__/dist/code/37eeba0c55c171ce405fd46f7606f6f15454920f510a10ca38c8601925195b50/code/bybit.app.mjs:364:17)
    at Object.run (file:///tmp/__pdg__/dist/code/37eeba0c55c171ce405fd46f7606f6f15454920f510a10ca38c8601925195b50/code/actions/generic-api-call/generic-api-call.mjs:36:42)
    at null.executeComponent (/var/task/launch_worker.js:286:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:785:28)

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-03-06-105323.png?id=YR4VA5&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IllSNFZBNSIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcwOTY4MzY2NH0.985HC5iFwW-S4eC_bQs1bSLNlGqiJeT4tgLtedbrtOE&signature=089440f6982f4da68e63ce3899681e3dce13baa3b9870794a7f926f436185def)

**Comment by age0110** [comment]
![Screenshot 2024-03-06 110919](https://github.com/PipedreamHQ/pipedream/assets/2189558/09f49766-7b25-4990-abd8-5270e910c2bd)

extra screenshot with the settings

**Comment by sergio-eliot-rodriguez** [comment]
We can't support ByBit app beause it has the USA as a restricted country of operation.

Currently ByBit does not support connections from certain [restricted countries](https://www.bybit.com/en/help-center/article/Service-Restricted-Countries), included the United States. This appears in their services agreement:

```
As stated in Section 11.3 of the [Service Agreement](https://www.bybit.com/help-center/s/article/Bybit-Terms-of-Service), Bybit does not offer services or products to Users in a few excluded jurisdictions including the United States, the Chinese Mainland, Hong Kong, Singapore, Canada (...)
```
