### ISSUE TITLE
[BUG] 'import cairosvg' failing

### ISSUE THREAD

**Issue by jameskflanagan** [PipedreamHQ/pipedream#10998]
**Describe the bug**
when using 
`import cairosvg`

I get the following error:

```
Traceback (most recent call last):
  File "/tmp/__pdg__/dist/code/e3aabc97cd6875c399e2d8538f1be2e62f8d386ab46afef7c5fcc1587e25ccb2/code.py", line 2, in <module>
    import cairosvg
  File "/tmp/__pdg__/dist/python/cairosvg/__init__.py", line 26, in <module>
    from . import surface  # noqa isort:skip
    ^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/__pdg__/dist/python/cairosvg/surface.py", line 9, in <module>
    import cairocffi as cairo
  File "/tmp/__pdg__/dist/python/cairocffi/__init__.py", line 47, in <module>
    cairo = dlopen(
            ^^^^^^^
  File "/tmp/__pdg__/dist/python/cairocffi/__init__.py", line 44, in dlopen
    raise OSError(error_message)  # pragma: no cover
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: no library called "cairo-2" was found
no library called "cairo" was found
no library called "libcairo-2" was found
cannot load library 'libcairo.so.2': libcairo.so.2: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.so.2'
cannot load library 'libcairo.2.dylib': libcairo.2.dylib: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo.2.dylib'
cannot load library 'libcairo-2.dll': libcairo-2.dll: cannot open shared object file: No such file or directory.  Additionally, ctypes.util.find_library() did not manage to locate a library called 'libcairo-2.dll'
```

**To Reproduce**
1. Run python code in pipedream.com
2. Run `import cairosvg`
3. See error

**Expected behavior**
I assume the import should work but there are libraries missing

**Additional context**
I assume no additional context or screenshots are needed, this should be quite easy to reproduce

**Comment by malexanderlim** [comment]
Hi @jameskflanagan , unfortunately we are unable to support Python packages which rely on binaries that are not included with the package.

**Comment by jameskflanagan** [comment]
Ah too bad, thanks anyways
