### ISSUE TITLE
 Microsoft OneDrive

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11780]
### App
 Microsoft OneDrive

### Summary:
Error when new file uploaded

### Details:
The trigger is when a file is dropped into OneDrive. When we dropped in a file to the folder the workflow didn't trigger. It shows an error in the sources.

Here is the error message:
2024-05-01T16:35:17
error
Error: IDX14100: JWT is not well formed, there are no dots (.).
The token needs to be in JWS or JWE Compact Serialization Format. (JWS): 'EncodedHeader.EndcodedPayload.EncodedSignature'. (JWE): 'EncodedProtectedHeader.EncodedEncryptedKey.EncodedInitializationVector.EncodedCiphertext.EncodedAuthenticationTag'.
at GraphError (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/@microsoft+microsoft-graph-client@3.0.7/node_modules/@microsoft/microsoft-graph-client/src/GraphError.ts:63:3)
at Function.GraphErrorHandler.constructErrorFromResponse (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/@microsoft+microsoft-graph-client@3.0.7/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:77:18)
at Function.<anonymous> (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/@microsoft+microsoft-graph-client@3.0.7/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:104:31)
at step (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:195:27)
at Object.next (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:176:57)
at /pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:169:75
at new Promise (<anonymous>)
at Object.__awaiter (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/tslib@2.6.2/node_modules/tslib/tslib.js:165:16)
at Function.GraphErrorHandler.getError (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/@microsoft+microsoft-graph-client@3.0.7/node_modules/@microsoft/microsoft-graph-client/src/GraphErrorHandler.ts:101:65)
at GraphRequest.<anonymous> (/pipedream/dist/code/a1e920479cebf255fdf7b734df428fc94f884dbce114406f629763dd63cece9b/node_modules/.pnpm/@microsoft+microsoft-graph-client@3.0.7/node_modules/@microsoft/microsoft-graph-client/src/GraphRequest.ts:391:55)

### Screenshots:

![Screenshot](https://storage.tally.so/private/pipedream-error.png?id=G9ve9o&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Ikc5dmU5byIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcxNDU4MDIwMX0.jUUOSaQhFuTpT0d6_Iw5VySNXR7B4m__B3enS1VKqQo&signature=4a4ae0247563a3731a559571f747a9cefd3417a417b82085d6c340ca18cd2bdb)

**Comment by sergio-eliot-rodriguez** [comment]
:S

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
