### ISSUE TITLE
Brevo

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#11927]
### App
Brevo

### Summary:
Fails to add new contact when email not found

### Details:
I got this error in a recent workflow run. It makes no sense, because when the value passed to "Contact" (which can be an ID or email according to the docs) is not found, it should fall back on simply adding a new contact.

```
AxiosError - Request failed with status code 404
{"code":"document_not_found","message":"Contact does not exist"} 
    at null.settle (/pipedream/dist/code/f957e296eee733c4736681a2c09f0a8644d946f993b71c0e4d24807278ea53c3/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:1967:12)
    at Unzip.handleStreamEnd (/pipedream/dist/code/f957e296eee733c4736681a2c09f0a8644d946f993b71c0e4d24807278ea53c3/node_modules/.pnpm/axios@1.6.7/node_modules/axios/dist/node/axios.cjs:3066:11)
    at Unzip.emit (node:events:530:35)
    at null.endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.callAxios (/pipedream/dist/code/f957e296eee733c4736681a2c09f0a8644d946f993b71c0e4d24807278ea53c3/node_modules/.pnpm/@pipedream+platform@1.6.0/node_modules/@pipedream/platform/dist/axios.js:110:26)
    at Object.existingContactByIdentifier (file:///pipedream/dist/code/f957e296eee733c4736681a2c09f0a8644d946f993b71c0e4d24807278ea53c3/code/brevo.app.mjs:39:16)
    at Object.run (file:///pipedream/dist/code/f957e296eee733c4736681a2c09f0a8644d946f993b71c0e4d24807278ea53c3/code/actions/add-or-update-contact/add-or-update-contact.mjs:58:17)
    at null.executeComponent (/var/task/launch_worker.js:286:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:785:28)
(add_or_update_contact)
```

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-05-12-at-01.46.10.png?id=Qe77o7&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlFlNzdvNyIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcxNTQ3NDc4Mn0.kkFhFy68l8JIDogBqfUOC90upTXv66MYfGHhKIOhi14&signature=7e4943e1ab3108b329fe746202212a330d7a412f0ccd39ac843e196ae76627be)

**Comment by alexreg** [comment]
@vunguyenhung It seems the opposite issue is occurring now: it doesn't correctly handle the case when the contact already exists.

```
AxiosError - Request failed with status code 400
{"code":"duplicate_parameter","message":"Contact already exist"}
```

**Comment by alexreg** [comment]
@vunguyenhung I'm not sure how you're doing this in code, but you probably just want to set the `updateEnabled` parameter to true, as [per the documentation](https://developers.brevo.com/reference/createcontact).
