### ISSUE TITLE
Xero Accounting

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#12215]
### App
Xero Accounting

### Summary:
I am getting an error when I try to reconnect to Xero

### Details:
Hello

I'm getting this issue when I reconnect to Xero:

Sorry! Pipedream has reached their Xero connection limit, please let them know so they can connect more Xero organisations.

Due to this my apps are workflows are now also failing. e.g. in Framework: Staff Expense JF >> Xero:: Create Bill I am getting this error: 
TypeErrorCannot destructure property 'tenantId' of 'connections.filter(...)[0]' as it is undefined.
   at Object.default (file:///tmp/__pdee__/c_vZfxAArY/index.mjs:14:9)
   at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
   at MessagePort.messageHandler (/var/task/launch_worker.js:797:28)

In this workflow: Basketball: V2 Volunter Expense Form (1) >> Xero: Create Bill  I'm getting this error:
Error - Request failed with status code 500{"error":"{\"code\":\"EAUTH\",\"response\":\"535-5.7.8 Username and Password not accepted. For more information, go to\\n535 5.7.8 https://support.google.com/mail/?p=BadCredentials 6a1803df08f44-6ae4b406596sm29642266d6.99 - gsmtp\",\"responseCode\":535,\"command\":\"AUTH PLAIN\"}"}
{
  "error": "{\"code\":\"EAUTH\",\"response\":\"535-5.7.8 Username and Password not accepted. For more information, go to\\n535 5.7.8  https://support.google.com/mail/?p=BadCredentials 6a1803df08f44-6ae4b406596sm29642266d6.99 - gsmtp\",\"responseCode\":535,\"command\":\"AUTH PLAIN\"}"
}
   at null.createError (/opt/ee/node_modules/axios/lib/core/createError.js:16:15)
   at null.settle (/opt/ee/node_modules/axios/lib/core/settle.js:17:12)
   at IncomingMessage.handleStreamEnd (/opt/ee/node_modules/axios/lib/adapters/http.js:269:11)
   at IncomingMessage.emit (events.js:412:35)
   at null.endReadableNT (internal/streams/readable.js:1333:12)
   at process.processTicksAndRejections (internal/process/task_queues.js:82:21)

### Screenshots:

![Screenshot](https://storage.tally.so/private/Error-1.png?id=qDvWYO&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6InFEdldZTyIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTcxNzQxNDk0M30.2CEPgKI6W1vue0nMbUp_K-nZghKNXBHty-2w_KKw_7k&signature=1117bbda55cffc9568acbf63d4e09771deb7470b8995c7ee5f9fa7782ef50f60)

**Comment by malexanderlim** [comment]
The integration has been updated - you should now be able to connect your Xero account without issue.
