### ISSUE TITLE
[BUG] Google Drive - Cannot create file from template

### ISSUE THREAD

**Issue by LucBerge** [PipedreamHQ/pipedream#14138]
**Describe the bug**
I am not able to generate pdf file from google doc template using the `Create file from template` action.

**To Reproduce**
1. Create a file in google drive and get the id
2. Create a workflow with the `Google drive - Create file from template` action
3. In the `mode` field, select the `pdf` option
4. Test the step

**Expected behavior**
Pdf file created at the expected location.

**Current behavior**
```
FetchError

invalid json response body at https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart&alt=json reason: Unexpected token '<', "<html><hea"... is not valid JSON

Stack trace:
    at null.null (/tmp/__pdg__/dist/code/5a57c33732a575ac4ba9957da31e30c2a6f0a06d3587913bbc68d06658a177dd/node_modules/.pnpm/node-fetch@2.7.0/node_modules/node-fetch/lib/index.js:273:32)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.null (/tmp/__pdg__/dist/code/5a57c33732a575ac4ba9957da31e30c2a6f0a06d3587913bbc68d06658a177dd/node_modules/.pnpm/google-docs-mustaches@1.2.2/node_modules/google-docs-mustaches/lib/apis/fetch.js:25:27)
    at Object.run (file:///tmp/__pdg__/dist/code/5a57c33732a575ac4ba9957da31e30c2a6f0a06d3587913bbc68d06658a177dd/code/actions/create-file-from-template/create-file-from-template.mjs:91:21)
    at null.executeComponent (/var/task/launch_worker.js:292:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:792:28)
```

**Additional context**
- Component version : `0.1.5`
- It seams to be an error in the `google-docs-mustaches` package

**Comment by LucBerge** [comment]
@vunguyenhung You need to remove the curly braces in the action. `{{test}}:value1` -> `test:value1`

**Comment by LucBerge** [comment]
Hello, I saw there is a component update. I did it and it successfully worked. Looks like the last two commits from @andrewjschuang fixed this issue...
#14151
#14155
