### ISSUE TITLE
Notion: Append Block to Parent Action

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14159]
### App
Notion: Append Block to Parent Action
https://developers.notion.com/reference/patch-block-children

### Sources
N/A

### Actions
I would add the "Page Content" field in "Create Page from Database" should also be available in "Update Page".

**Comment by 0xAtomist** [comment]
I'm having trouble with Notion's "Append Block to Parent".
After many attempts on other functions, it seems this is meant to be the way to get page content to populate in a pre-existing database page.

everything I try I get the following error:

`this.createBlocks is not a function`

```
    at Object.run (file:///tmp/__pdg__/dist/code/9687b2e844ba2e198781dd61c8a8b3a3d38d53da6b89d262b683c278cbe67ba1/code/actions/append-block/append-block.mjs:84:28)
    at null.executeComponent (/var/task/launch_worker.js:292:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:792:28)
```

As referenced above (and in a separate issue), I would add the "Page Content" field in "Create Page from Database" to "Update Page".
