### ISSUE TITLE
Salesforce to Teams

### ISSUE THREAD

**Issue by pipedream-component-development** [PipedreamHQ/pipedream#14739]
### App
Salesforce to Teams

### Summary:
Python Code won't Execute 

### Details:
Command failed: pipreqs --force
INFO: Not scanning for jupyter notebooks.
ERROR: Failed on file: /pipedream/dist/code/1726648eeef5b55630ee1420fe50bf92846a79890a6c8bb5c78fc2c255772fa5/code.py
Traceback (most recent call last):
  File "/var/lang/bin/pipreqs", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/var/lang/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 609, in main
    init(args)
  File "/var/lang/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 533, in init
    candidates = get_all_imports(
                 ^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 153, in get_all_imports
    raise exc
  File "/var/lang/lib/python3.12/site-packages/pipreqs/pipreqs.py", line 139, in get_all_imports
    tree = ast.parse(contents)
           ^^^^^^^^^^^^^^^^^^^
  File "/var/lang/lib/python3.12/ast.py", line 52, in parse
    return compile(source, filename, mode, flags,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<unknown>", line 68
    "https://graph.microsoft.com/v1.0/directoryObjects/{id}",
TabError: inconsistent use of tabs and spaces in indentation

### Screenshots:

![Screenshot](https://storage.tally.so/private/Screenshot-2024-11-26-113954.png?id=VJBgJN&accessToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IlZKQmdKTiIsImZvcm1JZCI6Im5yampSdiIsImlhdCI6MTczMjY0MjgzOH0.M2WUNi2GfnVDheT_cKwtEGGaJnefjS7P51BuM93mzqQ&signature=95b1437edac25afeeddb4ef16e0f582f5980552efa5ced5a8696fb092f0af12e)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
