### ISSUE TITLE
[BUG] Zoom new meeting source payload undefined

### ISSUE THREAD

**Issue by ctrlaltdylan** [PipedreamHQ/pipedream#2322]
**Describe the bug**
The `zoom/source/meeting-started` source component assumes the payload will always contain and `object` property.

However, it appears Zoom doesn't always include this property and it's causing an error in customer workflows:

```javascript
TypeError: Cannot destructure property 'object' of 'payload' as it is undefined.
at Object.run (file:///var/task/user/sources/meeting-started/meeting-started.mjs:22:13)
at /var/task/index.js:123:72
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:61:20)
```

**To Reproduce**
1. Add your Zoom account
2. Create a "New meeting" source
3. Set trigger to "meeting.started"

**Expected behavior**
The source should not show an error message if there is no meeting currently.

**Additional context**
https://pipedream.com/community/t/zoom-meeting-telegram/1966

**Comment by vellames-turing** [comment]
Hey, I was not able to reproduce it, but I guess I found the issue :)

**Comment by dannyroosevelt** [comment]
This is ready for release!
