### ISSUE TITLE
[BUG] Can't create Google Sheets "New Row Added (Instant)" Trigger

### ISSUE THREAD

**Issue by qiuzilay** [PipedreamHQ/pipedream#2741]
**Describe the bug**
my workflow that was working normally 3 days ago suddenly had a problem today. After checking the log, found that the problem was in the Trigger. Trigger can't even be recreated.

TypeError: Cannot read property 'rowCount' of undefined
at file:///var/task/user/google_sheets/google_sheets.app.mjs:264:29
at Array.map (<anonymous>)
at Object.getWorksheetLength (file:///var/task/user/google_sheets/google_sheets.app.mjs:262:10)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async Object.getWorksheetLengthsById (file:///var/task/user/google_sheets/sources/common/new-row-added.mjs:64:32)
at async Object.processSpreadsheet (file:///var/task/user/google_sheets/sources/common/new-row-added.mjs:111:36)
at async Object.deploy (file:///var/task/user/google_sheets/sources/common/http-based/base.mjs:59:7)
at async /var/task/index.js:95:13
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:60:20)

**To Reproduce**
1. Go to https://pipedream.com/workflows
2. Click on New+ button to create a new workflow
3. Try to create a Google Sheets "New Row Added (Instant)" Trigger

**Expected behavior**
Create and run Trigger as normal.

**Screenshots**
![image](https://user-images.githubusercontent.com/60321475/166145539-6e9318aa-f053-494c-8357-c1f2bafa9bed.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Microsoft Edge
 - Version: 101.0.1210.32

**Comment by js07** [comment]
This bug seems to occur when a spreadsheet includes a tab of type 'OBJECT'. Reported in this slack thread: https://pipedream-users.slack.com/archives/CMZG4EBJ9/p1653444877581219
