### ISSUE TITLE
[BUG] Timeout in workflows not being respected

### ISSUE THREAD

**Issue by huzaifah-esm** [PipedreamHQ/pipedream#2950]
**Describe the bug**
My timeout is set to 750s but consistently seeing workflows being timed out after 30s.

```
TIMEOUT: TIMEOUT
    at Timeout._onTimeout (/var/task/lambda_handler.js:582:23)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
````

**Screenshots**
<img width="86" alt="image" src="https://user-images.githubusercontent.com/79848772/170225726-f0b81c17-6900-4213-99b8-0e1cd4c89ec6.png">
<img width="251" alt="image" src="https://user-images.githubusercontent.com/79848772/170225751-282bff60-0f36-4dee-9418-4a82182c0d81.png">

**Comment by ctrlaltdylan** [comment]
Hi @huzaifah-esm, sorry once events are deleted they are unrecoverable. I'm not going to be able to inspect those further.

But if this does happen again, please share the event ID and we'll happily take a look.
