### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by AlexeyArtemev** [PipedreamHQ/pipedream#2955]
**Describe the bug**
1.`Code was still running when the step ended` warning using the MongoDB integration in one workflow
2. The same MongoDB integration becomes unusable in other workflows

**To Reproduce**
Use MongoDB app's `search documents` option in the workflow
Test it with any Atlas DB deployments
Repeat in another workflow

**Expected behavior**
1. No warnings
2. No errors while using one MongoDB account in various workflows

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser: Chrome x64
 - Version 101.0.4951.67

**Additional context**
Initial workflow(available for support to edit) - pipedream.com/@AlexeyArtemiev/p_yKC1z9j
Details of error of using MongoDB integration in several workflows:
```
TypeError
Cannot destructure property 'username' of 'this.$auth' as it is null.
    at Object.connect (file:///tmp/ee/c_2jfA8lvB/user/mongodb.app.mjs:112:9)
    at null.null (file:///tmp/ee/c_2jfA8lvB/user/mongodb.app.mjs:237:14)
    at null.Promise (null:null:null)
    at Object.searchDocuments (file:///tmp/ee/c_2jfA8lvB/user/mongodb.app.mjs:236:14)
    at Object.run (file:///tmp/ee/c_2jfA8lvB/user/actions/search-documents/search-ducuments.mjs:25:45)
    at global.executeComponent (/var/task/launch_worker.js:134:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:597:28)
```

**Comment by ctrlaltdylan** [comment]
Hi @AlexeyArtemev ,

Thanks for the detailed bug report, but I'm unable to reproduce on my own MongoDB powered workflows.

The error may signal the issue: `Cannot destructure property 'username' of 'this.$auth' as it is null.`

Are you certain that your MongoDB credentials are populated? You can verify this by opening the **Connected Accounts** area and **Reconnect** your MongoDB account. It will show your credentials there.
