### ISSUE TITLE
[ACTION] Add entry to Notion database

### ISSUE THREAD

**Issue by valendinks** [PipedreamHQ/pipedream#3006]
**Is there a specific app this action is for?**
Notion

**Please provide a link to the relevant API docs for the specific service / operation.**
https://developers.notion.com/reference/post-page

**Description**
Presently, it's only possible to add subpages to a Notion page.
Ideally, the same integration can also add entries to a database, but would require to query the database first for the data format. See api docs above.

**Comment by dylburger** [comment]
Thanks for the request! Did you know that anyone can [author and publish their own Pipedream actions](https://pipedream.com/docs/components/quickstart/nodejs/actions/)? Would you be interested in helping out with that? We're happy to answer any questions or support you in any way.

If you don't have the time, would you be willing to reach out to the app provider to see if they're interested in building these? When we work with an app partner, it improves the quality of the integration, and it helps when this kind of request comes from a customer like you.

**Comment by nirurin** [comment]
I don't suppose you had any luck with this? Just spent an annoying few hours trying to get this working, before coming across this thread that basically said... no this doesn't work in pipedream haha. 

I have this working on timecamp already, but I'd rather use pipedream if it's possible. I'd appreciate hearing if you had any luck with it!

**Comment by valendinks** [comment]
None, I’m afraid.

The only way is directly through the API, but I’m not technical enough to
build something like that where it isn’t brittle as glass :)


søn. 5. jun. 2022 kl. 09.48 skrev nirurin ***@***.***>:

**Comment by nirurin** [comment]
https://pipedream.com/community/t/how-do-i-add-an-entry-to-a-notion-database/2465/6

This is the only thing I've found that may suggest an answer. Have you
gotten anything to work, even fragiley?

**Comment by andrewjschuang** [comment]
@valendinks @nirurin I'm working on this rn, would love your feedback when it's done!

**Comment by dannyroosevelt** [comment]
This is ready for release!

**Comment by andrewjschuang** [comment]
@valendinks @nirurin [these are the updates](https://github.com/PipedreamHQ/pipedream/pull/3126) to the Notion actions, including a new **Create Page From Database** that should solve your issue.

All defined database properties can be selected through the UI.
We currently support **To Do** and **Paragraph** children block types only, so if you need specific ones for your workflow you can [request them here](https://github.com/PipedreamHQ/pipedream/issues/new/choose).

**Comment by GiZmoFalcon** [comment]
I'm facing an issue here where the UI shows the properties selected, I can fill the value for each property, 

<img width="794" alt="image" src="https://user-images.githubusercontent.com/16624267/183203956-d47f8d73-43f8-4c8d-a855-e8f487fb6546.png">


but it errors out after running saying ```property.map.value``` is not a function.

And in the "inputs" section of the request, I see that the property field is empty. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/16624267/183202054-94022b6c-7e86-463e-adc3-7afb5af6c951.png">

```js 
TypeError
property.value.map is not a function

DETAILS
    at Object.convertToNotion (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/common/notion-page-properties.mjs:52:36)
    at Object._convertPropertiesToNotion (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:98:60)
    at Object._buildNotionPageProperties (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:128:19)
    at Object.buildPageProperties (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:155:19)
    at Object.buildPage (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/create-page-from-database/create-page-from-database.mjs:62:31)
    at Object.run (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/create-page-from-database/create-page-from-database.mjs:73:23)
    at process.processTicksAndRejections (internal/process/task_queues.js:95:5)
    at global.executeComponent (/var/task/launch_worker.js:142:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:614:28)
```

**Comment by andrewjschuang** [comment]
> I'm facing an issue here where the UI shows the properties selected, I can fill the value for each property,

Hi @GiZmoFalcon, thanks for the request! Can you [open a bug issue](https://github.com/PipedreamHQ/pipedream/issues/new?assignees=&labels=bug&template=bug_report.md&title=%5BBUG%5D+) please?
