### ISSUE TITLE
[BUG] The word "require" in string literals and comments causes Node code steps to throw in test mode and the Pipedream API to return an HTTP 500 status code upon publishing

### ISSUE THREAD

**Issue by ecobisi** [PipedreamHQ/pipedream#3187]
**Describe the bug**
There seems to be an issue with the regexp which performs the automatic import of dependencies for components and Node code steps, as it throws whenever it finds the word "require" in the source, no matter if it is in a comment section or in a string literal.

**To Reproduce**
*Steps to reproduce the behavior in the workflow designer (scenario 1)*:
1. Create a Node code step;
2. insert the word "require" as a string literal or as a comment, as in the following example:
```js
export default defineComponent({
  async run() {
    console.log('Extraordinary claims require extraordinary evidence.');
    return 42
  },
})
```
3. Click the test button and see the error message:
```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module' (4:0)
    at _class.pp$4.raise (/var/task/node_modules/acorn/dist/acorn.js:2927:15)
    at _class.pp$1.parseStatement (/var/task/node_modules/acorn/dist/acorn.js:870:18)
    at _class.parseStatement (/var/task/node_modules/acorn-node/lib/dynamic-import/index.js:65:118)
    at _class.pp$1.parseTopLevel (/var/task/node_modules/acorn/dist/acorn.js:755:23)
    at _class.parse (/var/task/node_modules/acorn/dist/acorn.js:555:17)
    at Function.parse (/var/task/node_modules/acorn/dist/acorn.js:578:37)
    at Object.parse (/var/task/node_modules/acorn-node/index.js:30:28)
    at parse (/var/task/node_modules/detective/index.js:22:18)
    at Function.exports.find (/var/task/node_modules/detective/index.js:47:15)
    at module.exports (/var/task/node_modules/detective/index.js:26:20)
```

*Steps to reproduce the behavior while publishing a component (scenario 2)*:
1. Create a component;
2. insert the word "require" as a string literal or as a comment, as mentioned above;
3. use the CLI to publish it (`pd publish ./test.mjs`) and see the error message:
```
component create api call responded with status: 500, body: {"error":"unexpected error, please contact support@pipedream.com"}
```

**Expected behavior**
Using that word should be allowed and of course shouldn't throw.

**Desktop (please complete the following information):**
 - OS: Linux 5.13.0-41-generic, Ubuntu 22.04 LTS 
 - Browser Chrome
 - Version 102.0.5005.115

Thank you

**Comment by DilanAthukorala** [comment]
@ecobisi I am able to reproduce this issue.

**Comment by dylburger** [comment]
This has been fixed!

<img width="932" alt="Screenshot 2023-08-01 at 9 00 10 PM" src="https://github.com/PipedreamHQ/pipedream/assets/242668/8b67684d-44a9-4047-ab15-f9a51390a824">
