### ISSUE TITLE
[BUG] Withings - TypeError: measures is not iterable

### ISSUE THREAD

**Issue by Defozo** [PipedreamHQ/pipedream#3403]
**Describe the bug**

I don't get any new events from Withings integration.

This is what I found in my logs:
```
TypeError: measures is not iterable
at Object.run (file:///var/task/user/sources/new-measure/new-measure.mjs:28:27)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
at async /var/task/index.js:122:11
at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
at async Runtime.exports.main [as handler] (/var/task/index.js:60:20)
```

**To Reproduce**
Unclear because it was working in the beginning.

**Expected behavior**
I expected new events from Withings integration with blood pressure and heart rate.

**Additional context**
I use the following nodejs code in my workflow. Would that break the integration somehow?

```
// To use any npm package, just import it
// import axios from "axios"

export default defineComponent({
  async run({ steps, $ }) {
    // Reference previous step data using the steps object and return data to use it in future steps
    
    let heartrate;
    let systolic;
    let diastolic;

    for (const measure of steps.trigger.event.measures) {
      switch (measure.type) {
        case 10:
          systolic = measure.value;
          break;
        case 11:
          heartrate = measure.value;
          break;
        case 9:
          diastolic = measure.value;
          break;
      }
    }
    let event1 = steps.trigger.event;
    var date = new Date(steps.trigger.event.date*1000);
    var formattedDate = date.toLocaleString("pl-PL", {timeZone: "Europe/Warsaw"}).replace(",","");
    return { event1, heartrate, systolic, diastolic, formattedDate }
  },
})
```

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
