### ISSUE TITLE
credential-provider-node error for aws-sdk

### ISSUE THREAD

**Issue by contd** [PipedreamHQ/pipedream#3504]
I tried to follow the best I could to setup a simple node js code step to get an delete a message from an SQS queue.  The code comes from the example and shown after the error log below:

```
Receive Error     at null.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+credential-provider-node@3.131.0/node_modules/@aws-sdk/credential-provider-node/dist-cjs/defaultProvider.js:13:11)
    at null.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+property-provider@3.127.0/node_modules/@aws-sdk/property-provider/dist-cjs/chain.js:11:28)
    at process.processTicksAndRejections (internal/process/task_queues.js:95:5)
    at null.coalesceProvider (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+property-provider@3.127.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:14:24)
    at SignatureV4.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+property-provider@3.127.0/node_modules/@aws-sdk/property-provider/dist-cjs/memoize.js:33:24)
    at SignatureV4.signRequest (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+signature-v4@3.130.0/node_modules/@aws-sdk/signature-v4/dist-cjs/SignatureV4.js:84:29)
    at null.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+middleware-signing@3.130.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:18)
    at StandardRetryStrategy.retry (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+middleware-retry@3.127.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at null.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+middleware-sdk-sqs@3.127.0/node_modules/@aws-sdk/middleware-sdk-sqs/dist-cjs/receive-message.js:7:22)
    at null.null (/tmp/__pdg__/dist/code/e894c02ae9180f82462575b91952eb68b61a4fcaf5e6b37ddae2e54f794c13d8/node_modules/.pnpm/@aws-sdk+middleware-logger@3.127.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22)
 {
  tryNextLink: false,
  name: 'CredentialsProviderError',
  '$metadata': { attempts: 1, totalRetryDelay: 0 }
}
```

Here is the code trying to run:

```js
import { 
      ReceiveMessageCommand,
      DeleteMessageCommand,
      SQSClient 
    } from "@aws-sdk/client-sqs"

export default defineComponent({
  props: {
    aws: {
      type: "app",
      app: "aws",
    }
  },
  async run({steps, $}) {
    const { accessKeyId, secretAccessKey } = this.aws.$auth    
    const REGION = "us-east-1"
    const queueURL = "https://sqs.us-east-1.amazonaws.com/xxxxxxx/queue"
    const params = {
      AttributeNames: ["SentTimestamp"],
      MaxNumberOfMessages: 10,
      MessageAttributeNames: ["All"],
      QueueUrl: queueURL,
      VisibilityTimeout: 20,
      WaitTimeSeconds: 0,
    }
    const sqsClient = new SQSClient({ 
      accessKeyId, 
      secretAccessKey,
      region: REGION 
    })
    try {
      const data = await sqsClient.send(new ReceiveMessageCommand(params));
      
      return data; // For unit tests.
    } catch (err) {
      console.log("Receive Error", err)
    }
    finally {
      // Reference previous step data using the steps object and return data to use it in future steps
      return steps.trigger.event
    }
  },
})
```

**Comment by dylburger** [comment]
@contd Thanks for reaching out. I believe the v3 AWS SDK you're using requires you pass credentials under a `credentials` object in the client constructor:

```javascript
const sqsClient = new SQSClient({ 
  credentials: {
    accessKeyId, 
    secretAccessKey,
  }
  region: REGION 
  })
```

Let us know if that works.

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
