### ISSUE TITLE
[BUG] property.map.value is not a function, when pushing data to notion database.

### ISSUE THREAD

**Issue by GiZmoFalcon** [PipedreamHQ/pipedream#4152]
I'm facing an issue here where the UI shows the properties selected, I can fill the value for each property, 

<img width="794" alt="image" src="https://user-images.githubusercontent.com/16624267/183203956-d47f8d73-43f8-4c8d-a855-e8f487fb6546.png">

but it errors out after running saying ```property.map.value``` is not a function.

And in the "inputs" section of the request, I see that the property field is empty. 

<img width="539" alt="image" src="https://user-images.githubusercontent.com/16624267/183202054-94022b6c-7e86-463e-adc3-7afb5af6c951.png">

```js 
TypeError
property.value.map is not a function

DETAILS
    at Object.convertToNotion (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/common/notion-page-properties.mjs:52:36)
    at Object._convertPropertiesToNotion (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:98:60)
    at Object._buildNotionPageProperties (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:128:19)
    at Object.buildPageProperties (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/common/base-page-builder.mjs:155:19)
    at Object.buildPage (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/create-page-from-database/create-page-from-database.mjs:62:31)
    at Object.run (file:///tmp/__pdg__/dist/code/4e0eaa7dbadfe9d398cc7f7ffbc8570f4bcf3770bd7362e8184bd6accc62cd9c/code/actions/create-page-from-database/create-page-from-database.mjs:73:23)
    at process.processTicksAndRejections (internal/process/task_queues.js:95:5)
    at global.executeComponent (/var/task/launch_worker.js:142:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:614:28)
```

**Comment by andrewjschuang** [comment]
Hey @GiZmoFalcon, can you try inputting `[ "test" ]` for the prop `tags`?

**Comment by Hassan-Abbas-SQA** [comment]
@GiZmoFalcon @GiZmoFalcon First TestCase for running this action in a simple way and selecting tags from already provided values it seems to be working fine for me 
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188273847-c347b7d7-534e-46fa-b628-b7c8f326dbd5.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188273865-c621939b-97a3-4099-8a1e-f4bdac5026c5.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188273874-82bbad15-cb03-4c10-93df-306575ff23d2.png">

**Comment by Hassan-Abbas-SQA** [comment]
@andrewjschuang @GiZmoFalcon Second TestCase: iam inserting Tags as Andrew described ["Test"] as custom value but it didn’t work for me may be Notion only wants you to select the already available tags and not insert any of custom values in it 

<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188274118-7bfe5e9c-528f-4063-9c52-4834f3e3413e.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188274124-312e9a3e-91cf-4dc5-ab01-217150c81c88.png">
<img width="905" alt="image" src="https://user-images.githubusercontent.com/104946677/188274139-c5888a13-c53c-407b-9d9c-9e07bb6eedc0.png">

**Comment by Hassan-Abbas-SQA** [comment]
Test Passed works fine now
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/104946677/194142091-d6eaf112-cd60-4318-8356-014ae4ccc1a5.png">
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/104946677/194142139-b9610806-e82a-4e4d-820a-74d8e1c73851.png">
