### ISSUE TITLE
[BUG][aws_s3_stream_file] Error when streaming SVG files - A header you provided implies functionality that is not implemented - Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.

### ISSUE THREAD

**Issue by Vadorequest** [PipedreamHQ/pipedream#4463]
**Describe the bug**
I'm getting an error when trying to store a SVG file into S3.

I tried using `https://dl.airtable.com/.attachments/7d49003c78419a9857790918194e931d/2ea5ca4f/US-logo-black.svg` file.

```
A header you provided implies functionality that is not implemented
at null.throwDefaultError (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+smithy-client@3.186.0/node_modules/@aws-sdk/smithy-client/dist-cjs/default-error-handler.js:8:22)
    at null.deserializeAws_restXmlPutObjectCommandError (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+client-s3@3.186.0/node_modules/@aws-sdk/client-s3/dist-cjs/protocols/Aws_restXml.js:5781:43)
    at process.processTicksAndRejections (internal/process/task_queues.js:95:5)
    at null.null (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+middleware-serde@3.186.0/node_modules/@aws-sdk/middleware-serde/dist-cjs/deserializerMiddleware.js:7:24)
    at null.null (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+middleware-signing@3.186.0/node_modules/@aws-sdk/middleware-signing/dist-cjs/middleware.js:13:20)
    at StandardRetryStrategy.retry (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+middleware-retry@3.186.0/node_modules/@aws-sdk/middleware-retry/dist-cjs/StandardRetryStrategy.js:51:46)
    at null.null (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+middleware-flexible-checksums@3.186.0/node_modules/@aws-sdk/middleware-flexible-checksums/dist-cjs/flexibleChecksumsMiddleware.js:56:20)
    at null.null (/tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/node_modules/.pnpm/@aws-sdk+middleware-logger@3.186.0/node_modules/@aws-sdk/middleware-logger/dist-cjs/loggerMiddleware.js:6:22)
    at Object.run (file:///tmp/__pdg__/dist/code/5fa66f4f464d941ad29e6e7e2b6af89ad402468ecb870a0cb26e3877cae07f21/code/actions/s3-stream-file/s3-stream-file.mjs:23:22)
    at global.executeComponent (/var/task/launch_worker.js:146:22)
```

Logs detail
```
Are you using a Stream of unknown length as the Body of a PutObject request? Consider using Upload instead from @aws-sdk/lib-storage.

```

**To Reproduce**
[See Video](https://watch.screencastify.com/v/NkNznaS8odFvRe6TRsHN)

**Expected behavior**
It should work for SVG as it does for PNG.

**Screenshots**
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/3807458/194900193-60770eed-5cf6-46af-bdc8-1405a99922fb.png">

<img width="956" alt="image" src="https://user-images.githubusercontent.com/3807458/194900596-7e1eb249-bf56-4ed0-9d10-d39cc8631716.png">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Brave

**Additional context**
I believe SVG need to be handled differently?

**Comment by vunguyenhung** [comment]
Hello @Vadorequest, thank you so much for providing a very clear detail. I have added this to our component backlog. Please subscribe to this issue as all updates will be made to this issue 🙏

**Comment by Vadorequest** [comment]
I tried uploading a SVG file following that fix and still got the same error, I guess it isn't deployed yet?

<img width="603" alt="image" src="https://user-images.githubusercontent.com/3807458/199586362-777b084e-030b-4b7c-94d6-51658f97ee08.png">

**Comment by dannyroosevelt** [comment]
@Vadorequest did you update to the latest version of the action? Can you confirm what version is still not working for you? The latest should be `0.3.1`.

**Comment by Vadorequest** [comment]
I'm using the cloud version, not sure how I'm supposed to update or see the version there.

**Comment by dannyroosevelt** [comment]
You should see a red "Update" button at the top right corner of the "AWS - Stream File" action in your workflow.

After you test a step in your workflow, you should see 4 tabs: (Exports, Inputs, Logs, Details)

If you click on "Details", you should see the Version (note, this screenshot is a different action than the one you are using):
![Screenshot by Dropbox Capture](https://user-images.githubusercontent.com/20780753/199605394-97458aa2-4997-4f60-ae1d-f8e0e8c7ca5d.png)

**Comment by Vadorequest** [comment]
Indeed, had to update the action. All good now! Thanks!

**Comment by dannyroosevelt** [comment]
Great! 🚀
