### ISSUE TITLE
[BUG] SFTP Upload File (Key-based auth) throws error Cannot parse privateKey

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5024]
**Describe the bug**
SFTP Upload File (Key-based auth) throws error Cannot parse privateKey. This can be reproduced by both Open SSH 2048-bit and 3072-bit

**To Reproduce**
1. Create a new Workflow
2. Setup a new FTP server, import the 2048-bit or 3072-bit public-private keypair with OpenSSH format
3. Add a new action SFTP Upload File (Key-based auth), add the private key content
4. Test the action
5. See error
```
connect: Cannot parse privateKey: Unsupported key format

DETAILS
    at SftpClient.fmtError (/tmp/__pdg__/dist/code/d1d364ce7a87b24841e535bcd4c2409ce742c01e385c321e9568af1c7c54868c/node_modules/.pnpm/ssh2-sftp-client@9.0.4/node_modules/ssh2-sftp-client/src/index.js:111:22)
    at SftpClient.connect (/tmp/__pdg__/dist/code/d1d364ce7a87b24841e535bcd4c2409ce742c01e385c321e9568af1c7c54868c/node_modules/.pnpm/ssh2-sftp-client@9.0.4/node_modules/ssh2-sftp-client/src/index.js:249:37)
    at Object.run (file:///tmp/__pdg__/dist/code/d1d364ce7a87b24841e535bcd4c2409ce742c01e385c321e9568af1c7c54868c/component.mjs:40:5)
    at global.executeComponent (/var/task/launch_worker.js:139:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:598:28)
```

**Expected behavior**
The SFTP app should accept 2048-bit private key format, or we need to communicate with user on the correct format

**Additional context**
First reported by the user here: https://pipedream.com/community/t/sftp-upload-file-key-based-auth-integration-cannot-parse-privatekey/4020

**Comment by DilanAthukorala** [comment]
Verification success for all type of keys.
