### ISSUE TITLE
[BUG] Shopify Partners - New App Relationship Events doesn't emit new events

### ISSUE THREAD

**Issue by vunguyenhung** [PipedreamHQ/pipedream#5188]
**Describe the bug**
Shopify Partners - New App Relationship Events doesn't emit new events. The source log show the following error
```

error
/var/task/node_modules/graphql-request/src/index.ts:497
throw new ClientError(
^
Error: Invalid GID '24472715265'. Global ID's use the following format 'gid://partners/$ModelName/$ModelId': {"response":{"data":{"app":null},"errors":[{"message":"Invalid GID '24472715265'. Global ID's use the following format 'gid://partners/$ModelName/$ModelId'","locations":[{"line":9,"column":5}],"path":["app"],"extensions":{"code":"INVALID_GID"}}],"status":200,"headers":{}},"request":{"query":"\n query getAppRelationshipEventsBackwards(\n $appId: ID!\n $occurredAtMin: DateTime\n $occurredAtMax: DateTime\n $after: String\n $recordsPerRun: Int\n ) {\n app(id: $appId) {\n events(\n types: [RELATIONSHIP_INSTALLED, RELATIONSHIP_UNINSTALLED, RELATIONSHIP_DEACTIVATED, SUBSCRIPTION_CHARGE_ACCEPTED, SUBSCRIPTION_CHARGE_ACTIVATED, SUBSCRIPTION_CHARGE_CANCELED, SUBSCRIPTION_CHARGE_DECLINED, SUBSCRIPTION_CHARGE_FROZEN, \nSUBSCRIPTION_CHARGE_UNFROZEN]\n occurredAtMin: $occurredAtMin\n occurredAtMax: $occurredAtMax\n after: $after\n first: $recordsPerRun\n ) {\n pageInfo {\n hasNextPage\n }\n edges {\n cursor\n node {\n occurredAt\n __typename\n ... on RelationshipUninstalled {\n reason\n description\n app {\n id\n name\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on RelationshipInstalled {\n app {\n id\n name\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on RelationshipDeactivated {\n app {\n id\n name\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on RelationshipReactivated {\n app {\n id\n name\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeAccepted {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeActivated {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeCanceled {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeDeclined {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeFrozen {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n ... on SubscriptionChargeUnfrozen {\n app {\n id\n name\n }\n charge {\n amount {\n currencyCode\n amount\n }\n billingOn\n id\n name\n test\n }\n shop {\n avatarUrl\n id\n myshopifyDomain\n name\n }\n }\n }\n }\n }\n }\n }\n","variables":{"appId":"24472715265","recordsPerRun":50}}}
at null.<anonymous> (/var/task/node_modules/graphql-request/src/index.ts:497:11)
at step (/var/task/node_modules/graphql-request/dist/index.js:63:23)
at Object.next (/var/task/node_modules/graphql-request/dist/index.js:44:53)
at fulfilled (/var/task/node_modules/graphql-request/dist/index.js:35:58)
at processTicksAndRejections (internal/process/task_queues.js:95:5)
```
![09 36 12 - 16 - 01 - 2023](https://user-images.githubusercontent.com/18277920/212586548-d14f0e85-6e24-4659-bd39-037a7d9a5948.png)

**To Reproduce**
1. On Pipedream, follows the instruction to create a new Shopify Partner account and connect it to Pipedream
2. Create a new source: Shopify Partners - New App Relationship Events
3. Observe the source log
![09 36 12 - 16 - 01 - 2023](https://user-images.githubusercontent.com/18277920/212586548-d14f0e85-6e24-4659-bd39-037a7d9a5948.png)

**Expected behavior**
The source should emit new events, no error in the source log.

**Additional context**
First reported by a customer here: https://pipedream-users.slack.com/archives/CPTJYRY5A/p1673721421597189

**Comment by ctrlaltdylan** [comment]
@vunguyenhung @michelle0927 

This error is due to users inputing a scalar integer into the App ID prop on this source.

The source expects a graphql resource format like `gid://partner/App/${appId}`
