### ISSUE TITLE
[BUG] Jira integration is failing when epic type is selected

### ISSUE THREAD

**Issue by getlocaladmin** [PipedreamHQ/pipedream#5742]
**Describe the bug**
When trying to create Jira issue with issue type Epic the test fails. Changing it to Story it works

**To Reproduce**
1. Create jira integration
2. Select issue type epic
3. Map all the required fields
4. Test

**Expected behavior**
Issue is created as an epic

**Screenshots**
![image](https://user-images.githubusercontent.com/113044451/225404706-f7a1d9c6-fcba-43be-a953-96f478b2b356.png)
`Error - Request failed with status code 400
{"errorMessages":[],"errors":{"customfield_10011":"Epic Name is required."}}

DETAILS
    at null.createError (/tmp/__pdg__/dist/code/380f38009041873d069038d3746bc0ef05a21e0b0561657a84e7dd68f2f5fb56/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/createError.js:16:15)
    at null.settle (/tmp/__pdg__/dist/code/380f38009041873d069038d3746bc0ef05a21e0b0561657a84e7dd68f2f5fb56/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/tmp/__pdg__/dist/code/380f38009041873d069038d3746bc0ef05a21e0b0561657a84e7dd68f2f5fb56/node_modules/.pnpm/axios@0.21.4/node_modules/axios/lib/adapters/http.js:269:11)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)`

**Comment by vunguyenhung** [comment]
![image](https://user-images.githubusercontent.com/18277920/225691886-2538a5ed-2afa-4c29-94b1-5d7f73c9c263.png)
I can reproduce this issue
