### ISSUE TITLE
[BUG] Unable to import python thirdweb sdk

### ISSUE THREAD

**Issue by toinfinifty** [PipedreamHQ/pipedream#5836]
**Describe the bug**
I'm unable to import the thirdweb sdk in the python code workflow.

**To Reproduce**
from thirdweb import ThirdwebSDK

**Expected behavior**
I'm able to import this package

**Screenshots**

**Desktop (please complete the following information):**
 - chrome browser version 111.0.5563.66

**Smartphone (please complete the following information):**

**Additional context**
package exists on pypi at https://pypi.org/project/thirdweb-sdk/

ERROR MESSAGE
ModuleNotFoundError
No module named 'thirdweb'

DETAILS
Traceback (most recent call last):

  File "/nano-py/pipedream/worker.py", line 95, in load
    self.step_modules[cell["id"]] = importlib.import_module(cell["importPath"])

  File "/var/lang/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)

  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import

  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load

  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked

  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked

  File "<frozen importlib._bootstrap_external>", line 850, in exec_module

  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "/tmp/__pdg__/dist/code/e064cf58774ceb69755b4b5df3a2634869f5bc1ae3b938573948f7fa2765462b/code.py", line 1, in <module>
    from thirdweb import ThirdwebSDK

ModuleNotFoundError: No module named 'thirdweb'

**Comment by vunguyenhung** [comment]
Hello @toinfinifty, would you mind trying to add this line to specify the package?
```
# pipedream add-package thirdweb-sdk
```

You can refer to the doc here for more information https://pipedream.com/docs/code/python/#if-your-package-s-import-name-differs-from-its-pypi-package-name

**Comment by toinfinifty** [comment]
@vunguyenhung that worked! I'll let you know if I run across any other issues with this.
