### ISSUE TITLE
[BUG] Python azure-storage-blob package (.cache/pip' or its parent directory is not owned or is not writable by the current user)

### ISSUE THREAD

**Issue by jzumwalt** [PipedreamHQ/pipedream#6283]
**Describe the bug**
Python code step which uses azure-storage-blob fails to build

**To Reproduce**
`# pipedream add-package azure-storage-blob
from azure.storage.blob import BlobServiceClient`
 
Run the workflow

Error
`
Command failed: python3 -m pip install --target=/tmp/__pdg__/dist/python -r requirements.txt --upgrade WARNING: The directory '/home/sbx_user1051/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you should use sudo's -H flag. error: subprocess-exited-with-error × python setup.py egg_info did not run successfully. │ exit code: 1 ╰─> [25 lines of output] Traceback (most recent call last): File "<string>", line 2, in <module> File "<pip-setuptools-caller>", line 34, in <module> File "/tmp/pip-install-cbx5gwap/azure_76476e1e714a460b83e3dacf602c4180/setup.py", line 60, in <module> raise RuntimeError(message) RuntimeError: Starting with v5.0.0, the 'azure' meta-package is deprecated and cannot be installed anymore. Please install the service specific packages prefixed by `azure` needed for your application. The complete list of available packages can be found at: https://aka.ms/azsdk/python/all Here's a non-exhaustive list of common packages: - azure-mgmt-compute (https://pypi.python.org/pypi/azure-mgmt-compute) : Management of Virtual Machines, etc. - azure-mgmt-storage (https://pypi.python.org/pypi/azure-mgmt-storage) : Management of storage accounts. - azure-mgmt-resource (https://pypi.python.org/pypi/azure-mgmt-resource) : Generic package about Azure Resource Management (ARM) - azure-keyvault-secrets (https://pypi.python.org/pypi/azure-keyvault-secrets) : Access to secrets in Key Vault - azure-storage-blob (https://pypi.python.org/pypi/azure-storage-blob) : Access to blobs in storage accounts A more comprehensive discussion of the rationale for this decision can be found in the following issue: https://github.com/Azure/azure-sdk-for-python/issues/10646 [end of output] note: This error originates from a subprocess, and is likely not a problem with pip. error: metadata-generation-failed × Encountered error while generating package metadata. ╰─> See above for output. note: This is an issue with the package mentioned above, not pip. hint: See above for details. WARNING: You are using pip version 22.0.4; however, version 23.1.2 is available. You should consider upgrading via the '/var/lang/bin/python3 -m pip install --upgrade pip' command.`

**Expected behavior**
The workflow will build and can run

**Comment by jzumwalt** [comment]
Same error here: https://github.com/PipedreamHQ/pipedream/issues/6260

**Comment by csarigoz** [comment]
Do you happen to have any updates regarding this matter? Are there any alternative solutions available?

**Comment by andrewjschuang** [comment]
[Another azure package request:](https://github.com/PipedreamHQ/pipedream/issues/4183#issuecomment-1375108099)

```
# pipedream add package azure-storage-file-datalake
from azure.storage.filedatalake import DataLakeServiceClient
```

**Comment by markvh033** [comment]
Im running into this too
