### ISSUE TITLE
[ACTION] what cause the error and how to fix this?

### ISSUE THREAD

**Issue by vincehor** [PipedreamHQ/pipedream#6636]
**Is there a specific app this action is for?**

**Please provide a link to the relevant API docs for the specific service / operation.**
https://pipedream.com/@bblabsdigital02/ascenbblabs-survey-p_zACv9Kn/build

I used the new row created on Google sheet trigger to add new subs to my Klaviyo by pulling First Name, Surname and email. I got this error. I looked around for a solution but this is beyond me to solve.

Error
Bad Request

DETAILS
    at Request.Request.callback (/tmp/__pdg__/dist/code/a2a02941800265e6fa7b64b8f3b64ec628dfab17813d787ade6b367de6e89488/node_modules/.pnpm/superagent@7.1.5/node_modules/superagent/lib/node/index.js:921:17)
    at null.null (/tmp/__pdg__/dist/code/a2a02941800265e6fa7b64b8f3b64ec628dfab17813d787ade6b367de6e89488/node_modules/.pnpm/superagent@7.1.5/node_modules/superagent/lib/node/index.js:1165:20)
    at IncomingMessage.null (/tmp/__pdg__/dist/code/a2a02941800265e6fa7b64b8f3b64ec628dfab17813d787ade6b367de6e89488/node_modules/.pnpm/superagent@7.1.5/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (events.js:412:35)
    at null.endReadableNT (internal/streams/readable.js:1333:12)
    at process.processTicksAndRejections (internal/process/task_queues.js:82:21)

**Comment by vunguyenhung** [comment]
Hi @vincehor, I believe this error is from Klaviyo. Since I couldn't access your workflow, could you share the screenshots of your actions and steps?

**Comment by vincehor** [comment]
@vunguyenhung vunguyenhung

**Comment by vunguyenhung** [comment]
Hi @vincehor, I see that the data you passed in is invalid (the Email having the text "Email Address"). I would suggest you to **select another event in your trigger** to test

As this is not a Pipedream issue, I will close this issue
