### ISSUE TITLE
[BUG] YouTube Data API Throttling

### ISSUE THREAD

**Issue by nickv2002** [PipedreamHQ/pipedream#741]
**Describe the bug**
YouTube Data API is 403ing

**To Reproduce**

1. Call YouTube Data API using PD managed authentication
2. See 403 logged:

```
2020-12-28T18:18:55 error
Error: Request failed with status code 403
at createError (/var/task/node_modules/axios/lib/core/createError.js:16:15)
at settle (/var/task/node_modules/axios/lib/core/settle.js:17:12)
at IncomingMessage.handleStreamEnd (/var/task/node_modules/axios/lib/adapters/http.js:244:11)
at IncomingMessage.emit (events.js:326:22)
at endReadableNT (_stream_readable.js:1223:12)
at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Expected behavior**
No 403

New copy of of https://github.com/PipedreamHQ/pipedream/issues/339

**Comment by todsac** [comment]
We do have some limits in place for the YouTube Data api.  What are your queries per day and per minute?

**Comment by todsac** [comment]
I made some adjustments to the limits so this should be resolved. Please confirm.

**Comment by nickv2002** [comment]
Able to get YT events now. Thanks!

> We do have some limits in place for the YouTube Data api. What are your queries per day and per minute?

I want to check a few times a day for new videos on a playlist (or from among my subscriptions: https://github.com/PipedreamHQ/pipedream/issues/740). Not sure the point cost of these queries but as long as it runs at last once a day that's fine.

**Comment by todsac** [comment]
That should be no issue!

**Comment by dylburger** [comment]
We're observing some new quota error related to YouTube, and we're following up with the YouTube team to address this.

**Comment by dylburger** [comment]
We resolved this soon after the original report on June 14th, and forgot to close this issue. Closing now!
