### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by heet2201** [PipedreamHQ/pipedream#7740]
**Describe the bug**
Cannot able to create product in shopify from google sheet

**Expected behavior**
On every new row in google sheet, one of the shopify product creation should take place.

**Screenshots**
<img width="916" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/43903682/8c289273-51b4-4f1e-95ed-1473172acd5d">

**Additional context**
I was trying to connect gogole sheet and shopify store. Where on every row represent a new product in the sheet. The Google sheet connector is working as expected, and data is also flowing to the next connector (i.e. Shopify)...

But shopify is giving below error while creating product.

```
Error
301 - Moved Permanently - ""

DETAILS
    at Object._throwFormattedError (file:///tmp/__pdg__/dist/code/fc5e29118fb17b730e3be3747f69648615e95c29d0310d693ecc99fedcf6d60b/code/common-app.mjs:479:13)
    at Object.resourceAction (file:///tmp/__pdg__/dist/code/fc5e29118fb17b730e3be3747f69648615e95c29d0310d693ecc99fedcf6d60b/code/common-app.mjs:597:14)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/fc5e29118fb17b730e3be3747f69648615e95c29d0310d693ecc99fedcf6d60b/code/actions/create-product/common.mjs:15:21)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)

```

Also, if you could elaborate about Image option while creating shopify product through connector... that would also be very helpful. Let's say I have AWS url of image (signed url with authentication keys) then, how could we upload them in shopify connector.. (like base64 conversion or simple AWS url should also be work?)

Can you please help here?
Thanks for your time!

**Comment by heet2201** [comment]
Hi @jcortes , thanks for the help. Here is the sample raw form which I am trying to create shopify product.

`Handle | Title | Body (HTML) | Vendor | Product Category | Type | Tags | Published | Option1 Name | Option1 Value | Option2 Name | Option2 Value | Option3 Name | Option3 Value | Variant SKU | Variant Grams | Variant Inventory Tracker | Variant Inventory Qty | Variant Inventory Policy | Variant Fulfillment Service | Variant Price | Variant Compare At Price | Variant Requires Shipping | Variant Taxable | Variant Barcode | Image Src | Image Position | Image Alt Text | Gift Card | SEO Title | SEO Description | Google Shopping / Google Product Category | Google Shopping / Gender | Google Shopping / Age Group | Google Shopping / MPN | Google Shopping / AdWords Grouping | Google Shopping / AdWords Labels | Google Shopping / Condition | Google Shopping / Custom Product | Google Shopping / Custom Label 0 | Google Shopping / Custom Label 1 | Google Shopping / Custom Label 2 | Google Shopping / Custom Label 3 | Google Shopping / Custom Label 4 | Variant Image | Variant Weight Unit | Variant Tax Code | Cost per item | Price / International | Compare At Price / International | Status`
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
example-t-shirt | Example T-Shirt |   | Acme | Apparel & Accessories > Clothing | Shirts | min2 | TRUE | Title | Lithograph - Height: 9" x Width: 12" |   |   |   |   |   | 3629 |   | 100 | deny | manual | 25 |   | TRUE | TRUE |   | https://burst.shopifycdn.com/photos/green-t-shirt.jpg?width=5000 | 1 |   | FALSE | Our awesome T-shirt in 70 characters or less. | A great description of your products in 320 characters or less | Apparel & Accessories > Clothing | Unisex | Adult | 7X8ABC910 | T-shirts | cotton, pre-shrunk | used | FALSE |   |   |   |   |   |   | g |   |   |   |   | active

Attaching sample mapping in shopify connector as well:
<img width="883" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/43903682/7c0c76cd-c9d0-449f-85cb-b1d697a094aa">
<img width="890" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/43903682/63a81e9b-7a2d-4af4-b25e-cbb02b6e84aa">

Please let me know if you need any other help.

**Comment by heet2201** [comment]
Hi @jcortes, I have tried out shared workflow... but giving similar kind of error
Here is the detail of both steps:

<img width="910" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/43903682/741fa395-c247-411a-a905-a6377230a397">

<img width="891" alt="image" src="https://github.com/PipedreamHQ/pipedream/assets/43903682/6e510ff9-21ef-4c6f-aa26-65b514cf2d53">

**Comment by heet2201** [comment]
@jcortes it's giving this error:

```
Error
MaxRedirectsError: Redirected 10 times. Aborting.

DETAILS
    at Object.run (file:///tmp/__pdg__/dist/code/0ebf9de6690589783daafc41e9d23135578c7e5d9ac5108d9fc2affab82c3975/component.mjs:41:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)
```

Logs:
```
{
  title: 'Example T-Shirt',
  productDescription: '',
  vendor: 'Acme',
  productType: 'Shirts',
  tags: 'min2',
  status: 'active',
  images: 'https://burst.shopifycdn.com/photos/green-t-shirt.jpg?width=5000'
}

```

```
    at Request._onResponseBase (/tmp/__pdg__/dist/code/0ebf9de6690589783daafc41e9d23135578c7e5d9ac5108d9fc2affab82c3975/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:859:35)
    at Request._onResponse (/tmp/__pdg__/dist/code/0ebf9de6690589783daafc41e9d23135578c7e5d9ac5108d9fc2affab82c3975/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:948:24)
    at ClientRequest.null (/tmp/__pdg__/dist/code/0ebf9de6690589783daafc41e9d23135578c7e5d9ac5108d9fc2affab82c3975/node_modules/.pnpm/got@11.8.6/node_modules/got/dist/source/core/index.js:962:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at ClientRequest.origin.emit (/tmp/__pdg__/dist/code/0ebf9de6690589783daafc41e9d23135578c7e5d9ac5108d9fc2affab82c3975/node_modules/.pnpm/@szmarczak+http-timer@4.0.6/node_modules/@szmarczak/http-timer/dist/source/index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
 {
  name: 'MaxRedirectsError',
  code: 'ERR_TOO_MANY_REDIRECTS',
  timings: undefined
}
```

**Comment by heet2201** [comment]
Thanks fro sharing. Doesn't seems to be helping... Right now I am using default shopify hosting only
