### ISSUE TITLE
[BUG] Twitter/X API not creating tweets/posts/whatever elon is calling them

### ISSUE THREAD

**Issue by NebularNerd** [PipedreamHQ/pipedream#7783]
**Describe the bug**
Twitter/X API is erroring out making a tweet again. Error as follows:
```
Error
Unexpected error (status code: undefined): {}

DETAILS
    at null.null (file:///tmp/__pdg__/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/code/twitter.app.mjs:426:25)
    at Object.createTweet (file:///tmp/__pdg__/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/code/twitter.app.mjs:989:15)
    at Object.run (file:///tmp/__pdg__/dist/code/dc814cd6c59810cf4a607e0a3ac5245f045d05e818bbbf1cb7e096aea9654f2c/code/actions/create-tweet/create-tweet.mjs:139:17)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)
```

No changes to workflow/sources etc.. in a very long time so no reason for it to fail, other items in workflow that use the same inputs are working ok.

**To Reproduce**
1. Goto any workflow that creates a Tweet
2. Try creating a Tweet

**Expected behavior**
Tweets should post OK

**Desktop (please complete the following information):**
 - OS: Win 10, Chrome or FireFox all latest updates

**EDIT/UPDATE**
I did try reconnecting the API, it flagged an error and said Pipedream have been notified.

**Comment by NebularNerd** [comment]
Hi @vunguyenhung,

I created a test tweet workflow and that works fine. 
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/0c4089d7-2358-4f32-aad4-a5e754c2bf66)

But for some reason a workflow which has not been modified in months (since #5953 when we had to change API methods)  suddenly stopped working, just for fun I recreated the step and that works. For some reason the existing step has either been corrupted or made no longer functional. The new `Create Tweet` seems to have a lot less optional variables, was there a change in the API and existing workflows were not updated?

![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/a9e7239e-1fbd-4f7a-adb8-fadc13576727)

New recreated step:
![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/154c765a-2042-4e0f-af0e-f631b9c5e1ce)


Old failed step:

![image](https://github.com/PipedreamHQ/pipedream/assets/8470449/bbb4c92a-4cba-4fa3-be86-cb9ec65a359b)

**Comment by NebularNerd** [comment]
Closing this issue. If others come across the same problem, try recreating the step.
