### ISSUE TITLE
[BUG] invite_user_to_channel Slack integration not working

### ISSUE THREAD

**Issue by Maxhodges** [PipedreamHQ/pipedream#8206]
**Describe the bug**
I can create a channel and post a message to it, but I get errors when I try to invite users to it.
Channel exists. I successfully post to it in a previous step.

**To Reproduce**
1. use the invite_user_to_channel Slack action

**Expected behavior**
successfully adds user to slack

![slack_oops](https://github.com/PipedreamHQ/pipedream/assets/957271/7e076009-ac30-4e65-a139-80744b14df62)
![slacvk1](https://github.com/PipedreamHQ/pipedream/assets/957271/6d73a69c-7934-4c95-a423-049d2cbba091)

```Error
An API error occurred: channel_not_found

DETAILS
    at null.platformErrorFromResult (/tmp/__pdg__/dist/code/a58ea1756dadd6e07d0522fa6d34aff435f075290006dee473d7721333f31e02/node_modules/.pnpm/@slack+web-api@6.9.0/node_modules/@slack/web-api/dist/errors.js:56:33)
    at WebClient.apiCall (/tmp/__pdg__/dist/code/a58ea1756dadd6e07d0522fa6d34aff435f075290006dee473d7721333f31e02/node_modules/.pnpm/@slack+web-api@6.9.0/node_modules/@slack/web-api/dist/WebClient.js:181:56)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at Object.run (file:///tmp/__pdg__/dist/code/a58ea1756dadd6e07d0522fa6d34aff435f075290006dee473d7721333f31e02/code/actions/invite-user-to-channel/invite-user-to-channel.mjs:25:12)
    at null.executeComponent (/var/task/launch_worker.js:229:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:726:28)```

**Desktop (please complete the following information):**
 - MaxOS 13.4.1 (c) (22F770820d)
 - Browser ARC Version 1.9.2 (41848)
 

**Additional context**
happy to join a call if someone would like to pair up and troubleshoot

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
