### ISSUE TITLE
[BUG] ChatGPT Classify Items Step throws "this.items.join is not a function" error

### ISSUE THREAD

**Issue by mythosmod** [PipedreamHQ/pipedream#8724]
**Describe the bug**
When testing the "classify_items_into_categories" step, the error "this.items.join is not a function" is returned

**To Reproduce**
Add ChatGPT "classify_items_into_categories" step
Add account, items and categories
Test and receive below error in results:

TypeError
this.items.join is not a function

DETAILS
    at Object.userMessage (file:///tmp/__pdg__/dist/code/d6c63d94477095eceaca8bd59c1b8ccb538d34284846044c5743edefd4186f07/code/actions/classify-items-into-categories/classify-items-into-categories.mjs:32:71)
    at Object.run (file:///tmp/__pdg__/dist/code/d6c63d94477095eceaca8bd59c1b8ccb538d34284846044c5743edefd4186f07/code/actions/common/common-helper.mjs:33:23)
    at null.executeComponent (/var/task/launch_worker.js:242:53)
    at MessagePort.messageHandler (/var/task/launch_worker.js:748:28)

**Expected behavior**
API call to chat GPT to classify item into categories

**Screenshots**
 
![image](https://github.com/PipedreamHQ/pipedream/assets/91185016/53adeb81-f3b5-4f5e-8191-15d563f2a5ac)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - Version Version 118.0.2088.76 (Official build) (64-bit)

**Comment by dylburger** [comment]
Without more information, I'm going to close this issue. Feel free to reopen and add more details, if you'd like.
