### ISSUE TITLE
[BUG] Onedrive - upload file - extension bug (easy fix?)

### ISSUE THREAD

**Issue by Rhydderch** [PipedreamHQ/pipedream#8938]
**Describe the bug**
When trying to upload a file to onedrive, I get the error that it cannot read the extension.
This error happens even though my file has an extension.

**To Reproduce**
- try to implement file upload with onedrive (in my case, a .md file)
- get an error regarding the extension

**Expected behavior**
The file has an extension so it should be uploaded without problem.

**Screenshots**
Error:
```
TypeError
Cannot read properties of undefined (reading 'ext')

DETAILS
    at Object.run (file:///tmp/__pdg__/dist/code/a1aafce9d85221e893cc06df06052a0b0b24e152098a9b40b1a3aea7b572f655/code/actions/upload-file/upload-file.mjs:60:56)
    at null.executeComponent (/var/task/launch_worker.js:242:22)
    at MessagePort.messageHandler (/var/task/launch_worker.js:748:28)
```

**Finding the bug**
I think the bug lies in the onedrive code:
[https://github.com/PipedreamHQ/pipedream/blob/master/components/microsoft_onedrive/actions/upload-file/upload-file.mjs](https://github.com/PipedreamHQ/pipedream/blob/master/components/microsoft_onedrive/actions/upload-file/upload-file.mjs) 

This line seems to be failing the component:
`const extension = (await fileTypeFromBuffer(data)).ext;`

It's weird that it's trying to grab the extension automatically even though a file name is already provided:
```
    const data = fs.readFileSync(filePath);
    const extension = (await fileTypeFromBuffer(data)).ext;
    const name = !filename.includes(".")
      ? `${filename}.${extension}`
      : filename;
```

**Desktop (please complete the following information):**
 NA
**Smartphone (please complete the following information):**
NA

**Additional context**

**Comment by Rhydderch** [comment]
Sorry for the late replay! I updated the component and I can confirm everything works well now. Thank you!!
