### ISSUE TITLE
[BUG] Salesforce: New Updated Field on Record triggers not functioning as expected

### ISSUE THREAD

**Issue by malexanderlim** [PipedreamHQ/pipedream#9362]
**Describe the bug**
Two of our registry Salesforce triggers only appear to be partially working - specifically, both the webhook and polling version of the trigger "New Updated Field on Record" only work in some cases. 

Certain object-field permutations fail.
1. New Updated Field on Record (Instant, of Selectable Type)
2. New Updated Field on Record (of Selectable Type)

**To Reproduce**
**Working Trigger configuration:** contact/title

**New Updated Field on Record (Instant, of Selectable Type)**
1. Object Type: Contact
Field Type: Title
In the Salesforce instance, edit an existing contact, and change the Title. You should see the event fire successfully.
<img width="999" alt="Screenshot 2023-12-18 at 3 56 38 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/099b067c-c920-4b10-a6a2-c68d94b92fe1">

**Broken Trigger configurations:** contact/title (polling), contact/email (webhook and polling)
1. The same object/field permutation does not work on the polling version:
**New Updated Field on Record (of Selectable Type)**
<img width="982" alt="Screenshot 2023-12-18 at 3 59 04 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/dc22b795-7fb6-46db-92ea-6bf2f74f9535">

**New Updated Field on Record (Instant, of Selectable Type)**

2.  
Object Type: Contact
Field Type: Email
A nondescript error, ```Error:
[object Object]
    at s._deployWebhook (/var/task/node_modules/salesforce-webhooks/dist/index.js:1:138666)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async s._createWebhookWorkflow (/var/task/node_modules/salesforce-webhooks/dist/index.js:1:138844)
    at async Object.activate (file:///var/task/user/sources/common-instant.mjs:34:23)
    at async /var/task/index.js:95:13
    at async captureObservations (/var/task/node_modules/@lambda-v2/component-runtime/src/captureObservations.js:28:5)
    at async exports.main [as handler] (/var/task/index.js:60:20)``` is returned when testing the Contact/Email permutation.
<img width="1227" alt="Screenshot 2023-12-18 at 4 02 01 PM" src="https://github.com/PipedreamHQ/pipedream/assets/42158621/4b526d9a-9a1c-4904-9527-48874a7aa44d">

3. This is also broken with the polling source, as no events fire.

**Expected Behavior:**
1. I expect the polling trigger to fire an event when the field that is being watched on an object is changed.
2. I expect the webhook (instant) trigger to return an event for valid permutations, and return a more descript error message if there is something wrong with the setup.

**Notes:**
The Salesforce setup is complex and somewhat difficult to navigate; I added step-by-step instructions detailing the permissions required to configure webhooks in [our documentation](https://pipedream.com/apps/salesforce-rest-api#getting-started).

**Comment by malexanderlim** [comment]
This may be related to a prior issue raised here:
https://github.com/PipedreamHQ/pipedream/issues/6130

**Comment by malexanderlim** [comment]
I broke out the other feature to reduce the number of API calls for the polling triggers here: https://github.com/PipedreamHQ/pipedream/issues/9479

I'd like to try to get this part shipped, and we can tackle the object-field permutation issue separately.

**Comment by daniel-adayev-prefect** [comment]
Hi, I recently had this issue. Not only did the instantaneous trigger not work, but the polling trigger seemed to be making WAY too many calls to salesforce, making around 200K api calls per day into our systems and maxing out our api call limits. 

I recommend setting up salesforce flow or salesforce apex triggers to send http requests to pipedream internally on record create or updates. This gives more visibility on api usage volume, increases speed of salesforce --> pipedream trigger, and saves on cost.

**Comment by malexanderlim** [comment]
Hi @daniel-adayev-prefect -  which trigger were you using specifically, and at what polling cadence? I saw your initial note and want to ensure that there isn't a bug with the polling version of the trigger, as the trigger should only poll at the cadence that you define. 

Thanks for the feedback as well around Salesforce Flow - happy to surface that as an option in our documentation as well.

**Comment by daniel-adayev-prefect** [comment]
> Hi @daniel-adayev-prefect - which trigger were you using specifically, and at what polling cadence? I saw your initial note and want to ensure that there isn't a bug with the polling version of the trigger, as the trigger should only poll at the cadence that you define.
> 
> Thanks for the feedback as well around Salesforce Flow - happy to surface that as an option in our documentation as well.

Hi @malexanderlim, thanks for the speedy response and sorry for jumping the gun and posting about the issue before trying to replicate it. We initially assumed it was due to the salesforce polling trigger in pipedream, but after some testing trying to replicate the issue in salesforce sandbox, we found out that it was caused by a different oauth connection that was sending thousands of api calls to salesforce and using up our entire api call allowance. This in turn prevented the pipedream salesforce polling triggers from working. 

At this point, the pipedream salesforce polling triggers work great however when setting up the "record updated instantaneous trigger", we get an "Error: [object Object] at async" when trying to save the trigger.
